"""GUI Translation Interface for Phase 4E Semantic Compression.

This module provides translation capabilities for converting compressed log formats
back to human-readable format, with special support for V5_SEMANTIC format.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Any, List, Union, Optional, Tuple
from collections import defaultdict

from .optimized_serializer import OptimizedEventSerializer, LogFormatVersion
from .format_migration import LogFormatMigrator
from .semantic_analyzer import SemanticAnalyzer


class LogFormatTranslator:
    """Translates compressed log formats back to human-readable format.
    
    Supports all format versions from V1_BASIC through V5_SEMANTIC,
    with special handling for semantic compression features.
    """
    
    def __init__(self):
        """Initialize the log format translator."""
        self.serializer = OptimizedEventSerializer()
        self.migrator = LogFormatMigrator()
        self.analyzer = SemanticAnalyzer()
        
        # Initialize translation dictionaries
        self._initialize_translation_dictionaries()
    
    def _initialize_translation_dictionaries(self) -> None:
        """Initialize dictionaries for translating compressed formats."""
        # Get reverse mappings from serializer
        self.pattern_to_behavior = self.serializer.get_pattern_to_behavior()
        self.dict_to_string = self.serializer.get_dict_to_string()
        
        # Create human-readable translations
        self.human_readable_translations = {
            # Event type translations
            'c': 'Collection Events',
            'm': 'Mode Change Events', 
            'o': 'Other Events',
            's': 'Step',
            't0': 'Timestamp',
            'dt': 'Delta Time',
            
            # Pattern translations
            '1': 'Pattern 1: Home→Forage, Resource Selection',
            '2': 'Pattern 2: Forage→Home, Collected Resource',
            'P3': 'Pattern 3: Forage→Idle, No Target Available',
            'P4': 'Pattern 4: Idle→Forage, Resource Selection',
            'P5': 'Pattern 5: Home→Idle, Deposited Goods',
            'P6': 'Pattern 6: Idle→Home, Force De',
            
            # Mode translations
            'f': 'Forage',
            'h': 'Home',
            'i': 'Idle',
            'm': 'Moving',
            't': 'Trading',
            'c': 'Collecting',
            'd': 'Depositing',
            
            # Transition translations
            'fh': 'Forage → Home',
            'hf': 'Home → Forage',
            'fi': 'Forage → Idle',
            'if': 'Idle → Forage',
            'hi': 'Home → Idle',
            'ih': 'Idle → Home',
        }
    
    def translate_log_file(self, input_path: Path, output_path: Path, 
                          format_version: Optional[LogFormatVersion] = None) -> Dict[str, Any]:
        """Translate a compressed log file to human-readable format.
        
        Args:
            input_path: Path to compressed log file
            output_path: Path to output human-readable file
            format_version: Specific format version (auto-detect if None)
            
        Returns:
            Translation statistics and metadata
        """
        translation_stats = {
            'input_path': str(input_path),
            'output_path': str(output_path),
            'total_steps': 0,
            'total_events': 0,
            'format_version': None,
            'compression_ratio': 0.0,
            'translation_errors': []
        }
        
        try:
            with open(input_path, 'r', encoding='utf-8') as infile:
                with open(output_path, 'w', encoding='utf-8') as outfile:
                    # Write header
                    outfile.write("# Human-Readable Log Translation\n")
                    outfile.write(f"# Source: {input_path.name}\n")
                    outfile.write(f"# Generated by VMT Log Translator\n\n")
                    
                    for line_num, line in enumerate(infile, 1):
                        line = line.strip()
                        if not line:
                            continue
                        
                        try:
                            log_data = json.loads(line)
                            
                            # Detect format version if not specified
                            if format_version is None:
                                format_version = self.migrator.detect_format_version(log_data)
                                translation_stats['format_version'] = format_version.value
                            
                            # Translate step data
                            translated_step = self.translate_step_data(log_data, format_version)
                            
                            # Write translated step
                            outfile.write(f"## Step {translated_step.get('step', 'Unknown')}\n")
                            outfile.write(f"Timestamp: {translated_step.get('timestamp', 'Unknown')}\n")
                            
                            # Write events
                            if 'events' in translated_step:
                                for event in translated_step['events']:
                                    outfile.write(f"- {event}\n")
                            
                            outfile.write("\n")
                            
                            # Update statistics
                            translation_stats['total_steps'] += 1
                            if 'events' in translated_step:
                                translation_stats['total_events'] += len(translated_step['events'])
                        
                        except json.JSONDecodeError as e:
                            error_msg = f"Invalid JSON on line {line_num}: {e}"
                            translation_stats['translation_errors'].append(error_msg)
                            outfile.write(f"# ERROR: {error_msg}\n\n")
                        except Exception as e:
                            error_msg = f"Translation error on line {line_num}: {e}"
                            translation_stats['translation_errors'].append(error_msg)
                            outfile.write(f"# ERROR: {error_msg}\n\n")
            
            # Calculate compression ratio
            if input_path.exists() and output_path.exists():
                input_size = input_path.stat().st_size
                output_size = output_path.stat().st_size
                if input_size > 0:
                    translation_stats['compression_ratio'] = (1 - input_size / output_size) * 100
        
        except FileNotFoundError:
            translation_stats['translation_errors'].append(f"Input file not found: {input_path}")
        except Exception as e:
            translation_stats['translation_errors'].append(f"Translation failed: {e}")
        
        return translation_stats
    
    def translate_step_data(self, step_data: Dict[str, Any], 
                           format_version: LogFormatVersion) -> Dict[str, Any]:
        """Translate a single step of compressed data to human-readable format.
        
        Args:
            step_data: Compressed step data
            format_version: Format version of the data
            
        Returns:
            Human-readable step data
        """
        translated = {
            'step': step_data.get('s', 'Unknown'),
            'timestamp': self._translate_timestamp(step_data),
            'events': []
        }
        
        # Translate events based on format version
        if format_version == LogFormatVersion.V5_SEMANTIC:
            translated['events'] = self._translate_v5_semantic_events(step_data)
        elif format_version == LogFormatVersion.V4_ULTRA:
            translated['events'] = self._translate_v4_ultra_events(step_data)
        elif format_version == LogFormatVersion.V3_ADVANCED:
            translated['events'] = self._translate_v3_advanced_events(step_data)
        elif format_version == LogFormatVersion.V2_OPTIMIZED:
            translated['events'] = self._translate_v2_optimized_events(step_data)
        else:
            translated['events'] = self._translate_v1_basic_events(step_data)
        
        return translated
    
    def _translate_timestamp(self, step_data: Dict[str, Any]) -> str:
        """Translate timestamp data to human-readable format.
        
        Args:
            step_data: Step data dictionary
            
        Returns:
            Human-readable timestamp string
        """
        if 'dt' in step_data:
            # Delta timestamp
            delta = step_data['dt']
            return f"Delta: +{delta}s"
        elif 't0' in step_data:
            # Absolute timestamp
            timestamp = step_data['t0']
            return f"{timestamp}s"
        else:
            return "Unknown"
    
    def _translate_v5_semantic_events(self, step_data: Dict[str, Any]) -> List[str]:
        """Translate V5_SEMANTIC format events to human-readable format.
        
        Args:
            step_data: Step data dictionary
            
        Returns:
            List of human-readable event strings
        """
        events = []
        
        # Translate collection events
        if 'c' in step_data:
            collection_events = self._translate_semantic_collection_events(step_data['c'])
            events.extend(collection_events)
        
        # Translate mode events
        if 'm' in step_data:
            mode_events = self._translate_semantic_mode_events(step_data['m'])
            events.extend(mode_events)
        
        # Translate other events
        if 'o' in step_data:
            other_events = self._translate_semantic_other_events(step_data['o'])
            events.extend(other_events)
        
        return events
    
    def _translate_semantic_collection_events(self, collection_data: Union[str, List]) -> List[str]:
        """Translate semantic collection events to human-readable format.
        
        Args:
            collection_data: Collection event data
            
        Returns:
            List of human-readable collection event strings
        """
        events = []
        
        if isinstance(collection_data, str):
            # String format: "t0,1-5,7,9-12"
            events.append(self._translate_collection_string(collection_data))
        elif isinstance(collection_data, list):
            for item in collection_data:
                if isinstance(item, str):
                    events.append(self._translate_collection_string(item))
                elif isinstance(item, list):
                    events.append(self._translate_collection_list(item))
        
        return events
    
    def _translate_collection_string(self, collection_string: str) -> str:
        """Translate collection string to human-readable format.
        
        Args:
            collection_string: Collection string like "t0,1-5,7,9-12"
            
        Returns:
            Human-readable collection event string
        """
        parts = collection_string.split(',')
        if len(parts) < 2:
            return f"Collection: {collection_string}"
        
        timestamp = parts[0]
        agent_data = ','.join(parts[1:])
        
        # Translate timestamp
        time_desc = self.human_readable_translations.get(timestamp, timestamp)
        
        # Parse and translate agent data
        agent_list = self._parse_agent_range(agent_data)
        agent_desc = self._format_agent_list(agent_list)
        
        return f"Collection Event - Time: {time_desc}, Agents: {agent_desc}"
    
    def _translate_collection_list(self, collection_list: List) -> str:
        """Translate collection list to human-readable format.
        
        Args:
            collection_list: Collection list data
            
        Returns:
            Human-readable collection event string
        """
        if len(collection_list) >= 2:
            timestamp = collection_list[0]
            agent_data = collection_list[1]
            
            time_desc = self.human_readable_translations.get(timestamp, timestamp)
            
            if isinstance(agent_data, str):
                agent_list = self._parse_agent_range(agent_data)
            else:
                agent_list = agent_data if isinstance(agent_data, list) else [agent_data]
            
            agent_desc = self._format_agent_list(agent_list)
            return f"Collection Event - Time: {time_desc}, Agents: {agent_desc}"
        
        return f"Collection Event: {collection_list}"
    
    def _translate_semantic_mode_events(self, mode_data: Union[str, List]) -> List[str]:
        """Translate semantic mode events to human-readable format.
        
        Args:
            mode_data: Mode event data
            
        Returns:
            List of human-readable mode event strings
        """
        events = []
        
        if isinstance(mode_data, str):
            # String format: "1,t0,1-5" or "t0,6,fi,nta"
            events.append(self._translate_mode_string(mode_data))
        elif isinstance(mode_data, list):
            for item in mode_data:
                if isinstance(item, str):
                    events.append(self._translate_mode_string(item))
                elif isinstance(item, list):
                    events.append(self._translate_mode_list(item))
        
        return events
    
    def _translate_mode_string(self, mode_string: str) -> str:
        """Translate mode string to human-readable format.
        
        Args:
            mode_string: Mode string like "1,t0,1-5" or "t0,6,fi,nta"
            
        Returns:
            Human-readable mode event string
        """
        parts = mode_string.split(',')
        if len(parts) < 3:
            return f"Mode Change: {mode_string}"
        
        # Check if it's pattern format or individual format
        if parts[0].isdigit() or parts[0].startswith('P'):
            # Pattern format: "1,t0,1-5"
            pattern = parts[0]
            timestamp = parts[1]
            agent_data = ','.join(parts[2:])
            
            pattern_desc = self.human_readable_translations.get(pattern, f"Pattern {pattern}")
            time_desc = self.human_readable_translations.get(timestamp, timestamp)
            agent_list = self._parse_agent_range(agent_data)
            agent_desc = self._format_agent_list(agent_list)
            
            return f"Mode Change - {pattern_desc} - Time: {time_desc}, Agents: {agent_desc}"
        else:
            # Individual format: "t0,6,fi,nta"
            timestamp = parts[0]
            agent_id = parts[1]
            transition = parts[2]
            reason = parts[3] if len(parts) > 3 else "Unknown"
            
            time_desc = self.human_readable_translations.get(timestamp, timestamp)
            transition_desc = self.human_readable_translations.get(transition, transition)
            reason_desc = self.dict_to_string.get(reason, reason)
            
            return f"Mode Change - Agent {agent_id} - {transition_desc} - Reason: {reason_desc} - Time: {time_desc}"
    
    def _translate_mode_list(self, mode_list: List) -> str:
        """Translate mode list to human-readable format.
        
        Args:
            mode_list: Mode list data
            
        Returns:
            Human-readable mode event string
        """
        if len(mode_list) == 2:
            # Pattern format: ["1", ["t0", "1-5"]]
            pattern = mode_list[0]
            time_agent_data = mode_list[1]
            
            pattern_desc = self.human_readable_translations.get(pattern, f"Pattern {pattern}")
            
            if isinstance(time_agent_data, list) and len(time_agent_data) == 2:
                timestamp = time_agent_data[0]
                agent_data = time_agent_data[1]
                
                time_desc = self.human_readable_translations.get(timestamp, timestamp)
                
                if isinstance(agent_data, str):
                    agent_list = self._parse_agent_range(agent_data)
                else:
                    agent_list = agent_data if isinstance(agent_data, list) else [agent_data]
                
                agent_desc = self._format_agent_list(agent_list)
                return f"Mode Change - {pattern_desc} - Time: {time_desc}, Agents: {agent_desc}"
        
        elif len(mode_list) == 4:
            # Individual format: ["t0", 6, "fi", "nta"]
            timestamp = mode_list[0]
            agent_id = mode_list[1]
            transition = mode_list[2]
            reason = mode_list[3]
            
            time_desc = self.human_readable_translations.get(timestamp, timestamp)
            transition_desc = self.human_readable_translations.get(transition, transition)
            reason_desc = self.dict_to_string.get(reason, reason)
            
            return f"Mode Change - Agent {agent_id} - {transition_desc} - Reason: {reason_desc} - Time: {time_desc}"
        
        return f"Mode Change: {mode_list}"
    
    def _translate_semantic_other_events(self, other_data: Union[str, List]) -> List[str]:
        """Translate semantic other events to human-readable format.
        
        Args:
            other_data: Other event data
            
        Returns:
            List of human-readable other event strings
        """
        events = []
        
        if isinstance(other_data, str):
            events.append(f"Other Event: {other_data}")
        elif isinstance(other_data, list):
            for item in other_data:
                if isinstance(item, dict):
                    event_desc = self._translate_event_dict(item)
                    events.append(f"Other Event: {event_desc}")
                else:
                    events.append(f"Other Event: {item}")
        
        return events
    
    def _translate_event_dict(self, event_dict: Dict[str, Any]) -> str:
        """Translate event dictionary to human-readable format.
        
        Args:
            event_dict: Event dictionary
            
        Returns:
            Human-readable event description
        """
        parts = []
        for key, value in event_dict.items():
            key_desc = self.human_readable_translations.get(key, key)
            if isinstance(value, str):
                value_desc = self.dict_to_string.get(value, value)
            else:
                value_desc = str(value)
            parts.append(f"{key_desc}: {value_desc}")
        
        return ", ".join(parts)
    
    def _translate_v4_ultra_events(self, step_data: Dict[str, Any]) -> List[str]:
        """Translate V4_ULTRA format events to human-readable format.
        
        Args:
            step_data: Step data dictionary
            
        Returns:
            List of human-readable event strings
        """
        # V4_ULTRA uses similar structure to V5_SEMANTIC but with different compression
        return self._translate_v5_semantic_events(step_data)
    
    def _translate_v3_advanced_events(self, step_data: Dict[str, Any]) -> List[str]:
        """Translate V3_ADVANCED format events to human-readable format.
        
        Args:
            step_data: Step data dictionary
            
        Returns:
            List of human-readable event strings
        """
        # Similar to V4_ULTRA but with different agent range compression
        return self._translate_v5_semantic_events(step_data)
    
    def _translate_v2_optimized_events(self, step_data: Dict[str, Any]) -> List[str]:
        """Translate V2_OPTIMIZED format events to human-readable format.
        
        Args:
            step_data: Step data dictionary
            
        Returns:
            List of human-readable event strings
        """
        # Similar structure but with P1, P2 pattern codes
        return self._translate_v5_semantic_events(step_data)
    
    def _translate_v1_basic_events(self, step_data: Dict[str, Any]) -> List[str]:
        """Translate V1_BASIC format events to human-readable format.
        
        Args:
            step_data: Step data dictionary
            
        Returns:
            List of human-readable event strings
        """
        events = []
        
        # V1_BASIC has different structure - handle accordingly
        for key, value in step_data.items():
            if key in ['s', 'step', 't', 'timestamp', 't0']:
                continue  # Skip metadata fields
            
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, dict):
                        event_desc = self._translate_event_dict(item)
                        events.append(f"{key.title()} Event: {event_desc}")
                    else:
                        events.append(f"{key.title()} Event: {item}")
            else:
                events.append(f"{key.title()}: {value}")
        
        return events
    
    def _parse_agent_range(self, range_string: str) -> List[int]:
        """Parse agent range string to list of agent IDs.
        
        Args:
            range_string: Agent range string like "1-5,7,9-12"
            
        Returns:
            List of agent IDs
        """
        agents = []
        parts = range_string.split(',')
        
        for part in parts:
            part = part.strip()
            if '-' in part:
                # Range: "1-5"
                start, end = map(int, part.split('-'))
                agents.extend(range(start, end + 1))
            else:
                # Single: "7"
                agents.append(int(part))
        
        return sorted(agents)
    
    def _format_agent_list(self, agent_list: List[int]) -> str:
        """Format agent list for human-readable display.
        
        Args:
            agent_list: List of agent IDs
            
        Returns:
            Formatted agent list string
        """
        if not agent_list:
            return "None"
        elif len(agent_list) == 1:
            return f"Agent {agent_list[0]}"
        elif len(agent_list) <= 5:
            return f"Agents {', '.join(map(str, agent_list))}"
        else:
            return f"Agents {agent_list[0]}-{agent_list[-1]} ({len(agent_list)} total)"


def create_log_translator() -> LogFormatTranslator:
    """Factory function to create a log format translator.
    
    Returns:
        Configured LogFormatTranslator instance
    """
    return LogFormatTranslator()
