#!/usr/bin/env python3
"""
Custom Generated Test: abc
Validates unified target selection behavior with mixed preferences

Auto-generated by Live Configuration Editor
Created: 2025-09-29 16:14:01
"""

import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from PyQt6.QtWidgets import QApplication
# Import from new framework location
sys.path.insert(0, str(project_root / "src"))
from econsim.tools.launcher.framework.base_test import StandardPhaseTest
from econsim.tools.launcher.framework.test_configs import TestConfiguration
from econsim.tools.launcher.framework.phase_manager import PhaseDefinition

# Custom phase configuration
CUSTOM_PHASES = [
    PhaseDefinition(
        number=1,
        turn_start=1,
        turn_end=100,
        description="Both foraging and exchange enabled",
        forage_enabled=True,
        trade_enabled=True
    ),
    PhaseDefinition(
        number=2,
        turn_start=101,
        turn_end=200,
        description="Only foraging enabled",
        forage_enabled=True,
        trade_enabled=False
    ),
]

# Custom test configuration
CUSTOM_CONFIG = TestConfiguration(
    id=999,
    name="abc",
    description="Validates unified target selection behavior with mixed preferences",
    grid_size=(30, 30),
    agent_count=20,
    resource_density=0.25,
    perception_radius=8,
    distance_scaling_factor=0.0,
    preference_mix="mixed",
    seed=12345,
    custom_phases=CUSTOM_PHASES
)

class CustomTest(StandardPhaseTest):
    """Custom test implementation."""
    
    def __init__(self):
        super().__init__(CUSTOM_CONFIG)

def main():
    """Run the custom test."""
    app = QApplication(sys.argv)
    test = CustomTest()
    test.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()
