#!/usr/bin/env python3
"""
Custom Generated Test: BIG TEST
Validates unified target selection behavior with mixed preferences

Auto-generated by Live Configuration Editor
Created: 2025-09-29 16:00:51
"""

import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from PyQt6.QtWidgets import QApplication
# Import from new framework location
sys.path.insert(0, str(project_root / "src"))
from econsim.tools.launcher.framework.base_test import StandardPhaseTest
from econsim.tools.launcher.framework.test_configs import TestConfiguration
from econsim.tools.launcher.framework.phase_manager import PhaseDefinition

# Custom phase configuration
CUSTOM_PHASES = [
    PhaseDefinition(
        number=1,
        turn_start=1,
        turn_end=2000,
        description="Only foraging enabled",
        forage_enabled=True,
        trade_enabled=False
    ),
    PhaseDefinition(
        number=2,
        turn_start=2001,
        turn_end=2020,
        description="Both systems disabled - agents should idle",
        forage_enabled=False,
        trade_enabled=False
    ),
    PhaseDefinition(
        number=3,
        turn_start=2021,
        turn_end=4020,
        description="Only exchange enabled",
        forage_enabled=False,
        trade_enabled=True
    ),
    PhaseDefinition(
        number=4,
        turn_start=4021,
        turn_end=4040,
        description="Both systems disabled - agents should idle",
        forage_enabled=False,
        trade_enabled=False
    ),
    PhaseDefinition(
        number=5,
        turn_start=4041,
        turn_end=6040,
        description="Both foraging and exchange enabled",
        forage_enabled=True,
        trade_enabled=True
    ),
    PhaseDefinition(
        number=6,
        turn_start=6041,
        turn_end=6060,
        description="Both systems disabled - agents should idle",
        forage_enabled=False,
        trade_enabled=False
    ),
    PhaseDefinition(
        number=7,
        turn_start=6061,
        turn_end=8060,
        description="Only exchange enabled",
        forage_enabled=False,
        trade_enabled=True
    ),
    PhaseDefinition(
        number=8,
        turn_start=8061,
        turn_end=8080,
        description="Only foraging enabled",
        forage_enabled=True,
        trade_enabled=False
    ),
    PhaseDefinition(
        number=9,
        turn_start=8081,
        turn_end=10080,
        description="Only exchange enabled",
        forage_enabled=False,
        trade_enabled=True
    ),
    PhaseDefinition(
        number=10,
        turn_start=10081,
        turn_end=10100,
        description="Both foraging and exchange enabled",
        forage_enabled=True,
        trade_enabled=True
    ),
]

# Custom test configuration
CUSTOM_CONFIG = TestConfiguration(
    id=999,
    name="BIG TEST",
    description="Validates unified target selection behavior with mixed preferences",
    grid_size=(30, 30),
    agent_count=50,
    resource_density=0.25,
    perception_radius=8,
    distance_scaling_factor=2.0,
    preference_mix="mixed",
    seed=12345,
    custom_phases=CUSTOM_PHASES
)

class CustomTest(StandardPhaseTest):
    """Custom test implementation."""
    
    def __init__(self):
        super().__init__(CUSTOM_CONFIG)

def main():
    """Run the custom test."""
    app = QApplication(sys.argv)
    test = CustomTest()
    test.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()
