#!/usr/bin/env python3
"""
Custom Generated Test: Canon
Long comprehensive test for performance and behavior baselines.

Auto-generated by Live Configuration Editor
Created: 2025-09-29 15:06:07
"""

import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from PyQt6.QtWidgets import QApplication
# Import from new framework location
sys.path.insert(0, str(project_root / "src"))
from econsim.tools.launcher.framework.base_test import StandardPhaseTest
from econsim.tools.launcher.framework.test_configs import TestConfiguration

# Custom test configuration
CUSTOM_CONFIG = TestConfiguration(
    id=999,
    name="Canon",
    description="Long comprehensive test for performance and behavior baselines.",
    grid_size=(40, 40),
    agent_count=80,
    resource_density=0.19,
    perception_radius=12,
    distance_scaling_factor=2.0,
    preference_mix="mixed",
    seed=12345
)

class CustomTest(StandardPhaseTest):
    """Custom test implementation."""
    
    def __init__(self):
        super().__init__(CUSTOM_CONFIG)

def main():
    """Run the custom test."""
    app = QApplication(sys.argv)
    test = CustomTest()
    test.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()
